-- db/migrate_rpg_attrs.sql
-- Adds RPG attribute columns to characters_base.
-- Safe to re-run: ADD COLUMN IF NOT EXISTS is idempotent.

ALTER TABLE characters_base
  ADD COLUMN IF NOT EXISTS str          SMALLINT     NOT NULL DEFAULT 10,
  ADD COLUMN IF NOT EXISTS dex          SMALLINT     NOT NULL DEFAULT 10,
  ADD COLUMN IF NOT EXISTS con          SMALLINT     NOT NULL DEFAULT 10,
  ADD COLUMN IF NOT EXISTS int          SMALLINT     NOT NULL DEFAULT 10,
  ADD COLUMN IF NOT EXISTS wis          SMALLINT     NOT NULL DEFAULT 10,
  ADD COLUMN IF NOT EXISTS cha          SMALLINT     NOT NULL DEFAULT 10,
  ADD COLUMN IF NOT EXISTS primary_attr VARCHAR(8)   NOT NULL DEFAULT 'str',
  ADD COLUMN IF NOT EXISTS skill_attr   VARCHAR(8)   NOT NULL DEFAULT 'str',
  ADD COLUMN IF NOT EXISTS weapon_bonus SMALLINT     NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS armor_bonus  SMALLINT     NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS spd_offset   NUMERIC(5,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sp_bonus     NUMERIC(6,3) NOT NULL DEFAULT 0;
